### ISSUE TITLE
Multiple issues getting this to run

### ISSUE THREAD

**Issue by jkundertgibbs** [hbilen/mcnDCGAN#3]
Hi, using matconvnet beta 20 I cannot get the code to run properly. 
Issue 1: the pathing is all screwed up in terms of where you need to be, currently, to run the code properly. I've kind of hacked this part.
Issue 2 (still haven't solved this one): `Undefined function or variable 'getImageBatch'.`
`Error in dcgan_train>getBatch (line 96)
data = getImageBatch(images, opts.(phase), 'prefetch', nargout == 0) ;`
I can't seem to find this function anywhere in the code. 
Issue 3: the code doesn't seem to generate an imdb--at least it's not in my variables list after starting the code. Could this be affecting issue 2?
Help on any of this would be great. Thanks!

**Comment by hbilen** [comment]
Hi, sorry. This code should work with newer versions of matconvnet. adam optimisation and getbatch functions did not exist in mcn beta 20. Can you try with the latest version and let me know?

**Comment by jkundertgibbs** [comment]
Hi, 

Yes, I was having issues compiling the latest version of matconvnet. When I was able to (link: https://www.mathworks.com/matlabcentral/answers/246507-why-can-t-mex-find-a-supported-compiler-in-matlab-r2015b-after-i-upgraded-to-xcode-7-0 - see the alternative fix, which worked fine for me.) I was able to run your code. It’s currently training. We will see how it turns out :)

**Comment by jkundertgibbs** [comment]
Actually, Hakan, a question for you: if I wish to start with a non-random image as my "generative" image, can you give me advice on how to do that? I assume it's in your dcgan_train_dag code (process epoch?) but am having a bit of difficulty figuring out exactly where the random image is created. My goal would be to read in an image at that point rather than randomly generate one. 
Thanks for the help!

**Comment by hbilen** [comment]
Indeed random image, "noise" variable is generated in processEpoch at lines 260-2. If you would like to read an image and pass it to netG or netD, it can be better to read in getBatch function in dcgan_train.m and add it to getBatch output. I hope this helps.

**Comment by jkundertgibbs** [comment]
That does help. I will look into it and let you know how it goes. Thank you very much for providing this code!
